### ISSUE TITLE
main page 구현 리스트

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-2-8#1]
- [x] 여행 상품 정보 (mock JSON) 를 활용하여 여행 상품 정보 노출
- [x] 리스트에서 노출해야 하는 정보: `idx, name, mainImage, price, spaceCategory`
- [x] 예약 버튼 생성 
- [x] 예약 버튼 클릭 시 여행 상품 장바구니에서 사용 할 수 있도록 상품 데이터를 저장
- [x] 여행 상품 정보 클릭 시 모달창을 통해 여행 상품을 자세히 안내
- [x] 모달에서 노출해야 하는 정보: `idx, name, mainImage, description, spaceCategory, price, maximumPurchases, registrationDate`

**Comment by jhoon9494** [comment]
## 이번 기능 Best-Practice: 호수님 PR #12 

아래 코멘트에 Best-Practice 선정 이유 작성해주세요!!

**Comment by jhoon9494** [comment]
- context API의 렌더링 이슈로 인해 context API가 아닌 redux/toolkit을 사용한 것
- 향후 각 페이지의 크기를 고려하여 코드 스플리팅을 사용한 것
- 코드 가독성

**Comment by hyorimcho** [comment]
- 각각 페이지가 커졌을때 한번에 많은 코드를 불러오면 초기 로딩이 늦어 질 수 있기 때문에  `lazy`와 `suspense`를 사용해서코드 스플리팅을 통해 번들링을 여러 파일로 분리해 필요할 때 하나 씩 불러옴
- toast 로 사용자에게 친절함

**Comment by Noeyso** [comment]
- reduxToolkit을 사용해서 장바구니,상품 상태를 전역적으로 잘 관리한 점
- toast ui를 사용해서 발생하는 이슈를 사용자에게 알려주어 처리한 점

**Comment by bokjunwoo** [comment]
- `lazy`, `suspense` 를 통한 코드 스플리팅을 통한 번들링 한 점
- reduxToolkit을 사용해서 장바구니상태를 전역적으로 구성 한 점
