### ISSUE TITLE
상품 필터 기능 구현 리스트

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-2-8#2]
## main page내 상품 필터링 기능
- [x] 가격 필터링 기능 (가격만 필터)
- [x] 공간(지역) 필터링 기능 (공간만 필터)
- [x] 다중 필터링 기능

**Comment by jhoon9494** [comment]
## Best-Practice: 지헌님 PR #18

**Comment by jhoon9494** [comment]
- 필터링에 사용되는 항목들을 utils로 묶어서 코드 분리
- useState와 useEffect로 상품 필터 기능을 구현한 것 (모든 상태를 전역적으로 관리할 필요가 없음)
- 공간 버튼의 토글 기능을 추가하여 한가지 공간만 선택하는 것이 아니라 다수의 공간을 필터링할 수 있도록 함.

**Comment by Noeyso** [comment]
- 코드 가독성
- 필터 기능을 ProductList 안에서 처리한점
- 사용되는 함수를 모듈화한 점 (utils)

**Comment by raw20** [comment]
- 필터링 항목을 전역적으로 관리할 필요가 없음.
- 관심사 분리가 잘 된점. 
- 그로 인해 전체적으로 코드 가독성이 좋음.

**Comment by hyorimcho** [comment]
- 새로 비동기 함수를 만들지 않고 `useState`, `useEffect` 로 필터링 한 점
- `utils` 에 함수를 따로 잘 분리한 점

**Comment by tnghgks** [comment]
- 전체적인 코드 가독성
- 재사용 가능한 함수들을 utils 폴더에 분리한 점
- 전역 상태 관리의 필요 유무를 잘 관리한 점
