### ISSUE TITLE
reservations page 구현 리스트

### ISSUE THREAD

**Issue by jhoon9494** [Wanted-PreOnboarding-Team-8/pre-onboarding-9th-2-8#3]
- [x] 저장한 여행 상품의 리스트 보여주기
- [x] 저장한 여행 상품 삭제
- [x] 여행 상품의 구매 수량 변경
- [x] 장바구니에 있는 여행 상품의 총 결제액 수를 계산하여 표시

**Comment by jhoon9494** [comment]
#29 Best Practice 이유
- 삭제 전 사용자에게 한 번 더 물어보는 과정
- 관심사에 따라 적절한 코드 분리
- 장바구니에 관련된 action을 한 가지로 통일한 후 commandType을 전달하여 각 type에 맞게 state를 변경하는 방식을 통해 action을 직접 사용하는 코드 단에서 코드의 길이가 줄어들고, 가독성이 좋아짐
- 장바구니에 담긴 배열에서 findIndex를 통해 배열의 전체 순회를 딱 한 번만 실행하고, index를 통해 상품에 직접 접근하여 state를 변경시켜주는 부분

**Comment by Noeyso** [comment]
#29 Best Practice 이유
- 중복되는 코드 모듈화
- Table을 사용해서 장바구니 ui를 깔끔하게 구현한 것

**Comment by tnghgks** [comment]
#29 Best Practice 이유

- 재사용성과 관심사에 따른 코드 분리
- UI 관련 포멧팅 함수 작성
- 적절한 커밋 태그와 추가적인 설명이 필요하면 작성한 커밋 본문
- 자주 사용되는 toast 메세지 같은 경우 중복되는 코드를 템플릿 생성기를 만들어 줄임

**Comment by hyorimcho** [comment]
#24 Best Practice 이유

- 전체 삭제, 선택 삭제 기능 구현
- 깔끔한 UI
- 장바구니 함수는 utils 로 적절하게 분리하여 추후 재사용 가능성 높임
- 적절한 커밋

**Comment by raw20** [comment]
https://github.com/Wanted-PreOnboarding-Team-8/pre-onboarding-9th-2-8/pull/29 Best Practice 이유

- 관심사에 따른 코드 분리가 잘 이루어짐
-  재사용을 위해 ui 관련 포맷팅 함수 작성

**Comment by greyHairChooseLife** [comment]
#29 Best Practice 이유

- ui와 로직 코드 분리가 잘 된 점
- redux state를 설계 할 때부터 사용 할 때를 고려한 점
